version: '3'

services:
  lab:
    image: jupyter/base-notebook
    volumes:
     - ./notebooks/:/notebooks
     - ./deps/:/deps
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=1
    command: start-notebook.sh --NotebookApp.notebook_dir=/notebooks